Political Algorithm ready to draft and test
thieunguyen5991/metaheuristics pull request #6
Opened 2022-11-29 22:03 UTC by ugomuhieddine17

Closes # 

## 📑 Description

The purpose of the pr is to introduce the PO algorithm to the draft repo. The PO.py and the run_PO.py files have been created.

## ✅ Checks

- [] My pull request adheres to the code style of this project
- [] My code requires changes to the documentation
- [] I have updated the documentation as required
- [] All the tests have passed

## ℹ Additional Information

2022-12-03 00:46 UTC, thieu1995 requested changes

2022-12-03 00:46 UTC, thieu1995 commented on models/multiple_solution/human_based/PO.py
> +                # Copy paste of what was above, since eq 10 already implemented
@ugomuhieddine17 can you see all of my comments?

2022-12-04 15:17 UTC, ugomuhieddine17 commented on models/multiple_solution/human_based/PO.py
> +        # first we make the constituencies
Each member is part of a party, and part of a constituency. It is just two different social organizations (one is a political group, and the second is the city council for example)

2022-12-04 15:24 UTC, ugomuhieddine17 commented on models/multiple_solution/human_based/PO.py
> +        if (self.fun(pji) <= self.fun(pjitminus1)):
done !

2022-12-04 15:25 UTC, ugomuhieddine17 commented on models/multiple_solution/human_based/PO.py
> +                # Copy paste of what was above, since eq 10 already implemented
it is a relict when we were coding altogether

2022-12-04 15:39 UTC, ugomuhieddine17 commented on models/multiple_solution/human_based/PO.py
> +        for i in range(len(parties)):
should be good now !

2022-12-04 15:39 UTC, ugomuhieddine17 commented on models/multiple_solution/human_based/PO.py
> +                    q = np.argmax(fitnesst[parties[r]])  # do we have to recompute here? or time consuming
relicat again

2022-12-04 15:40 UTC, ugomuhieddine17 commented on models/multiple_solution/human_based/PO.py
> +        # n = 3 parties, d = 2 dimensions
it is a relicat too, we indeed generalised n and d

2022-12-04 15:40 UTC, ugomuhieddine17 commented on models/multiple_solution/human_based/PO.py
> +                for j in range(len(party)):
done !

2022-12-04 15:41 UTC, ugomuhieddine17 commented on models/multiple_solution/human_based/PO.py
> +                for j in range(len(party)):
should I cancel this pull request and do a new one to be able to see the modifications?

2022-12-06 05:08 UTC, merged

2022-12-06 05:08 UTC, thieu1995 commented on models/multiple_solution/human_based/PO.py
> +                for j in range(len(party)):
@ugomuhieddine17 No need to do it.